# Generated by Django 5.1.4 on 2025-08-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=7),
            preserve_default=False,
        ),
    ]
