# Generated by Django 5.2.5 on 2025-10-09 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario_plato_and_more'),
        ('pedidos', '0016_detallepedido_hora_impresion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido'),
        ),
    ]
