# Generated by Django 5.2.5 on 2025-08-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('whatsapp_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('mostrar_precios_en_boleta', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_reporte', models.CharField(max_length=20)),
                ('total_ventas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ventas_menu_dia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ventas_carta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_plato_mas_vendido', models.PositiveIntegerField()),
                ('plato_mas_vendido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.plato')),
            ],
        ),
    ]
