# Generated by Django 5.2.5 on 2025-08-18 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_initial'),
        ('menu', '0003_plato_stock_actual_plato_stock_diario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteventa',
            name='ventas_productos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='cantidad_plato_mas_vendido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='plato_mas_vendido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.plato'),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='usuario_generador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='ventas_carta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='ventas_menu_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
