# Generated by Django 5.2.5 on 2025-08-18 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_reporteventa_ventas_productos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteventa',
            name='tipo_reporte',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='usuario_generador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='ventas_carta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='ventas_menu_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='ventas_productos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
