# Generated by Django 5.2.5 on 2025-08-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_reporteventa_tipo_reporte_and_more'),
        ('inventario', '0003_movimientoinventario_plato_and_more'),
        ('menu', '0003_plato_stock_actual_plato_stock_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteventa',
            name='cantidad_producto_mas_vendido',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporteventa',
            name='producto_mas_vendido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_producto', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='plato_mas_vendido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_plato', to='menu.plato'),
        ),
        migrations.AlterField(
            model_name='reporteventa',
            name='tipo_reporte',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=20),
        ),
    ]
