# Generated by Django 5.1.4 on 2025-08-09 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0004_remove_pedido_fecha_envio_cocina'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impreso', models.BooleanField(default=False)),
                ('fecha_impresion', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
    ]
