# Generated by Django 5.2.5 on 2025-08-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='preparado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_envio_cocina',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
