# Generated by Django 5.2.5 on 2025-08-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_detallepedido_preparado_mesa_capacidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_envio_cocina',
        ),
    ]
