# Generated by Django 5.1.4 on 2025-08-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Mañana (8am-3pm)'), ('TARDE', 'Tarde (3pm-12am)')], default='MAÑANA', max_length=10),
            preserve_default=False,
        ),
    ]
