# Generated by Django 5.1.4 on 2025-08-11 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_precio_venta'),
        ('menu', '0003_plato_stock_actual_plato_stock_diario'),
        ('pedidos', '0006_pedido_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.plato'),
        ),
    ]
