# Generated by Django 5.2.5 on 2025-09-12 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_alter_mesa_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefono_cliente',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='turno',
            field=models.CharField(blank=True, choices=[('MAÑANA', 'Mañana (8am-3pm)'), ('TARDE', 'Tarde (3pm-12am)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.cliente'),
        ),
    ]
