# Generated by Django 5.2.5 on 2025-10-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_cliente_remove_pedido_telefono_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='es_cortesia',
            field=models.BooleanField(default=False, help_text='Si es True, no suma en ventas ni caja'),
        ),
    ]
