# Generated by Django 5.2.5 on 2025-10-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_pedido_es_cortesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_diario',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
