# Generated by Django 5.2.5 on 2025-10-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_diario',
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
