# Generated by Django 5.2.5 on 2025-10-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_pedido_numero_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='hora_impresion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
