# Generated by Django 5.2.5 on 2025-08-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('MOZO', 'Mozo'), ('ADMIN', 'Administrador')], max_length=20),
        ),
    ]
