# Generated by Django 5.2.5 on 2025-08-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], max_length=10)),
                ('total_menu', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_carta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_general', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
