# Generated by Django 5.2.5 on 2025-08-09 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierrecaja',
            options={'ordering': ['-fecha', '-creado_en'], 'verbose_name': 'Cierre de Caja', 'verbose_name_plural': 'Cierres de Caja'},
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='total_carta',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='total_general',
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='total_menu',
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='diferencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='efectivo_reportado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='estado',
            field=models.CharField(choices=[('VENTAS_REGISTRADAS', 'Ventas registradas'), ('EFECTIVO_VERIFICADO', 'Efectivo verificado'), ('CERRADO', 'Cerrado')], default='VENTAS_REGISTRADAS', max_length=20),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='otros_medios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='tarjetas_reportadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_carta_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_menu_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='total_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='mozo',
            field=models.ForeignKey(limit_choices_to={'rol': 'mozo'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cierrecaja',
            name='turno',
            field=models.CharField(choices=[('MAÑANA', 'Mañana (8am-3pm)'), ('TARDE', 'Tarde (3pm-12am)')], max_length=10),
        ),
    ]
