# Generated by Django 5.2.5 on 2025-08-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_alter_cierrecaja_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierrecaja',
            name='total_otros_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
