# Generated by Django 5.2.5 on 2025-08-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_plato_categoria_delete_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plato',
            name='stock_diario',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
