# Generated by Django 5.2.5 on 2025-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_plato_stock_actual_plato_stock_diario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('menu', 'Menú del Día'), ('carta', 'Plato a la Carta'), ('entrada', 'Plato de Entrada')], max_length=10),
        ),
    ]
