# Generated by Django 5.2.5 on 2025-08-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_plato_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('menu', 'Menú del Día'), ('carta', 'Plato a la Carta'), ('entrada', 'Plato de Entrada Diario')], max_length=10),
        ),
    ]
