# Generated by Django 5.2.5 on 2025-08-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_plato_precio_alter_plato_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
