# Generated by Django 5.2.5 on 2025-09-05 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_plato_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatoDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('stock_diario', models.PositiveIntegerField(default=0)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.plato')),
            ],
            options={
                'unique_together': {('plato', 'fecha')},
            },
        ),
    ]
