# Generated by Django 5.2.5 on 2025-09-05 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_platodeldia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platodeldia',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='platodeldia',
            name='stock_diario',
        ),
    ]
