# Generated by Django 5.2.5 on 2025-09-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_platodeldia_stock_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='tipo',
            field=models.CharField(choices=[('menu', 'Menú del Día'), ('carta', 'Plato a la Carta'), ('entrada', 'Plato de Entrada Diario'), ('desayuno', 'Desayuno')], max_length=10),
        ),
    ]
